[tool.poetry]
name = "excel"
version = "0.1.0"
description = ""
authors = ["dadadamizhou <352278025@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
